### ISSUE TITLE
openbare mogelijkheid om te zien welke km-hokken inventarisatieachterstanden hebben

### ISSUE THREAD

**Issue by Baudewijnode** [floronnl/VA-issues#20]
Deze wens is geuit door meerdere mensen in de DC-gelederen. Nu kunnen alleen DC's en validatoren de tool (aantal soorten per hok / km-hok laatste keer goed onderzocht) zien waarmee het mogelijk is om te bepalen welke hokken al weer wat langer niet goed zijn onderzocht en weer een keer geactualiseerd mogen worden. Het zou mooi zijn als de kaart (met een aantal standaardinstellingen) voor een breder publiek (mensen met account bij VA) te bekijken is. Zo kunnen we waarnemers nog zelfstandiger maken en stimuleren om een km-hok te gaan inventariseren waarvan ze het idee hebben dat het nuttig is om er heen te gaan.

**Comment by laurenssparrius** [comment]
Dit was al mogelijk: deze kaart met de actualisatie is op kmhok-niveau is te zien voor iedereen (ook niet-ingelogden):

https://www.verspreidingsatlas.nl/dashboard/biodiversity.aspx?groep=V&kaarttype=LST
