### ISSUE TITLE
VA: naamgeving planten en vaatplanten gelijk trekken

### ISSUE THREAD

**Issue by WillemienTroelstra** [floronnl/VA-issues#21]
In de verspreidingsatlas is de volgorde van soortgroepen niet overal hetzelfde. Daarbij wordt in het menu linksboven 'planten' en op andere plekken 'vaatplanten' gebruikt.

Suggestie om daarbij ook de sortering van de soortgroepen gelijk te trekken, die verschilt nu per plek:
1. menu soortgroepen: hoofdindeling flora-fauna plus handmatig, 
2. plaatjes op de voorpagina en in dropdownlijsten om op soortgroep te filteren in het menu waarnemingen: (andere) handmatige indeling.
3. in de dropdownlijsten waarmee je soortgroep selecteert bij dashboard>kaart biodiversiteit per hok:  alfabetische volgorde.

**Comment by laurenssparrius** [comment]
Bedankt Willemien. Dit is nu overal aangepast.
